# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

inlineHeader = """
Copyright {{props["inceptionYear"]}} {{props["copyrightOwner"]}}
SPDX-License-Identifier: MIT
"""

includes = [
    "Dockerfile",
    "**/*.sh",
    "**/*.yml",
]

[properties]
inceptionYear = 2025
copyrightOwner = "Dotanuki Labs"
