# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint Bash Scripts
        uses: dotanuki-labs/github-actions/quality/bash@a7a632c1f8edc37e8d49b916363dba064e72e893

      - name: Check MIT license on source files
        uses: korandoru/hawkeye@62ea202c0bea0074eda7b1dc9f1edbb9d40827f7 # v7.0.0

      - name: Run Component Tests
        run: ./component-tests.sh
